default: &default
  adapter: postgresql
  encoding: unicode
  password:
  username: ubuntu
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: belt_exam_development


test:
  <<: *default
  database: belt_exam_test

production:
  <<: *default
  database: belt_exam_production
